import { NextResponse } from 'next/server'
import { and, eq } from 'drizzle-orm'
import { db } from '@/lib/db'
import { rechargeRequests, wallets, walletLedger } from '@/lib/db/schema'
import { getCurrentUser } from '@/lib/auth'
import { isAdminSessionValid } from '@/lib/admin-auth'

async function admin() { const user = await getCurrentUser(); return user?.role === 'admin' ? user : null }
export async function GET() { if (!await isAdminSessionValid() && !await admin()) return NextResponse.json({ error: 'Forbidden' }, { status: 403 }); const rows = await db.select().from(rechargeRequests).where(eq(rechargeRequests.status, 'pending')); return NextResponse.json({ requests: rows.filter(row => row.method.startsWith('withdrawal:')) }) }
export async function PATCH(request: Request) { const actor = await admin(); if (!actor) return NextResponse.json({ error: 'Forbidden' }, { status: 403 }); const body = await request.json().catch(() => null); const id = typeof body?.id === 'string' ? body.id : ''; const status = body?.status === 'approved' ? 'approved' : body?.status === 'rejected' ? 'rejected' : ''; if (!id || !status) return NextResponse.json({ error: 'Invalid review request.' }, { status: 400 }); const [item] = await db.select().from(rechargeRequests).where(and(eq(rechargeRequests.id, id), eq(rechargeRequests.status, 'pending'))).limit(1); if (!item || !item.method.startsWith('withdrawal:')) return NextResponse.json({ error: 'Request not found.' }, { status: 404 }); if (status === 'rejected') { await db.update(rechargeRequests).set({ status, reviewedBy: actor.id, reviewedAt: new Date() }).where(eq(rechargeRequests.id, id)); return NextResponse.json({ ok: true }) } const [wallet] = await db.select().from(wallets).where(eq(wallets.userId, item.userId)).limit(1); if (!wallet || wallet.balancePaise < item.amountPaise) return NextResponse.json({ error: 'Wallet balance is insufficient.' }, { status: 409 }); const nextBalance = wallet.balancePaise - item.amountPaise; await db.update(wallets).set({ balancePaise: nextBalance, updatedAt: new Date() }).where(eq(wallets.id, wallet.id)); await db.insert(walletLedger).values({ userId: item.userId, amountPaise: -item.amountPaise, balanceAfterPaise: nextBalance, type: 'withdrawal_debit', note: `Withdrawal to ${item.method.replace('withdrawal:', '')}` }); await db.update(rechargeRequests).set({ status, reviewedBy: actor.id, reviewedAt: new Date() }).where(eq(rechargeRequests.id, id)); return NextResponse.json({ ok: true }) }
