import { NextResponse } from 'next/server'
import { and, desc, eq } from 'drizzle-orm'
import { db } from '@/lib/db'
import { rechargeRequests, users, wallets, walletLedger } from '@/lib/db/schema'
import { getCurrentUser } from '@/lib/auth'
import { isAdminSessionValid } from '@/lib/admin-auth'

async function admin() { const user = await getCurrentUser(); return user?.role === 'admin' ? user : null }
export async function GET() { if (!await isAdminSessionValid() && !await admin()) return NextResponse.json({ error: 'Forbidden' }, { status: 403 }); const rows = await db.select({ id: rechargeRequests.id, userId: rechargeRequests.userId, amountPaise: rechargeRequests.amountPaise, method: rechargeRequests.method, upiId: rechargeRequests.upiId, accountName: rechargeRequests.accountName, accountNumber: rechargeRequests.accountNumber, ifscCode: rechargeRequests.ifscCode, utr: rechargeRequests.utr, status: rechargeRequests.status, createdAt: rechargeRequests.createdAt, name: users.name, email: users.email, phone: users.phone }).from(rechargeRequests).leftJoin(users, eq(users.id, rechargeRequests.userId)).where(eq(rechargeRequests.status, 'pending')).orderBy(desc(rechargeRequests.createdAt)); return NextResponse.json({ requests: rows.filter(row => row.method === 'withdrawal') }, { headers: { 'Cache-Control': 'no-store, max-age=0' } }) }
export async function PATCH(request: Request) { const actor = await admin(); const envAdmin = await isAdminSessionValid(); if (!actor && !envAdmin) return NextResponse.json({ error: 'Forbidden' }, { status: 403 }); const body = await request.json().catch(() => null); const id = typeof body?.id === 'string' ? body.id : ''; const status = body?.status === 'approved' ? 'approved' : body?.status === 'rejected' ? 'rejected' : ''; if (!id || !status) return NextResponse.json({ error: 'Invalid review request.' }, { status: 400 }); const [item] = await db.select().from(rechargeRequests).where(and(eq(rechargeRequests.id, id), eq(rechargeRequests.status, 'pending'))).limit(1); if (!item || item.method !== 'withdrawal') return NextResponse.json({ error: 'Request not found.' }, { status: 404 }); await db.transaction(async (tx) => { const [wallet] = await tx.select().from(wallets).where(eq(wallets.userId, item.userId)).for('update'); if (!wallet) throw new Error('WALLET_NOT_FOUND'); if (status === 'rejected') { const nextBalance = wallet.balancePaise + item.amountPaise; await tx.update(wallets).set({ balancePaise: nextBalance, updatedAt: new Date() }).where(eq(wallets.id, wallet.id)); await tx.insert(walletLedger).values({ userId: item.userId, amountPaise: item.amountPaise, balanceAfterPaise: nextBalance, type: 'withdrawal_refund', note: 'Withdrawal rejected; reserved amount returned' }); } await tx.update(rechargeRequests).set({ status, reviewedBy: actor?.id ?? null, reviewedAt: new Date() }).where(eq(rechargeRequests.id, id)) }).catch((error: unknown) => { if (error instanceof Error && error.message === 'WALLET_NOT_FOUND') throw new Error('Wallet not found.') ; throw error }); return NextResponse.json({ ok: true }) }
